---

- hosts: 127.0.0.1

  tasks:
  - name: destroy the management node
    shell: vagrant destroy -f
    register: vagrantresult
    args:
      chdir: /cygdrive/e/GIT/tmp/vagrant/utility
    async: 100000
    poll: 0

  - name: destroy the Kubernetes Cluster
    shell: vagrant destroy -f
    register: vagrantresult
    args:
      chdir: /cygdrive/e/GIT/tmp/vagrant/k8s-cluster
    async: 100000
    poll: 0

  - name: destroy the Consul Servers
    shell: vagrant destroy -f
    register: vagrantresult
    args:
      chdir: /cygdrive/e/GIT/tmp/vagrant/consul-servers
    async: 100000
    poll: 0

  - name: destroy Jenkins Server
    shell: vagrant destroy -f
    register: vagrantresult
    args:
      chdir: /cygdrive/e/GIT/tmp/vagrant/jenkins
    async: 100000
    poll: 0
