---
# tasks file for worker-nodes

- name: Build Workers | Configure Vagrantfile
  include: buildVagrant.yml

- name: Deploy Workers | Vagrant Up
  include: deployvagrant.yml

- name: Destroy Masters |  Vagrant Destroy
  include: vagrantdestroy.yml
  when: destroy == "yes"
