---
# tasks file for k8s Masters

- name: Build Masters | Configure Vagrantfile
  include: buildVagrant.yml

- name: Deploy Masters | Vagrant Up
  include: deployvagrant.yml

- name: Destroy Masters |  Vagrant Destroy
  include: vagrantdestroy.yml
  when: destroy == "yes"
